belgif/rest-guide

src/main/asciidoc/changelog.adoc
src/main/asciidoc/errorhandling.adoc
src/main/asciidoc/problems/badGateway.adoc
src/main/asciidoc/problems/internalServerError.adoc
src/main/asciidoc/problems/payloadTooLarge.adoc
src/main/asciidoc/problems/tooManyFailedRequests.adoc
src/main/asciidoc/problems/tooManyRequests.adoc

adds internalServerError, badGateway, tooManyFailedRequests, payloadTooLarge problem types
Adding the two last ones need to be validated by the WG.

#36 add 4 new standardized problem types

---

src/main/asciidoc/mediatypes.adoc

changes to guide to clarify usage of charset in media type ( #75 ) + add use of media type in OpenAPI 3
@wsalembi , could you review?

clarify charset in media type + use of media type in OpenAPI 3

---

src/main/asciidoc/errorhandling.adoc
src/main/asciidoc/problems/badRequest.adoc
src/main/asciidoc/problems/resourceNotFound.adoc
src/main/asciidoc/resources-document.adoc

input validation problem

---

src/main/asciidoc/resources-collection.adoc
src/main/asciidoc/resources.adoc

Add rule on filter query params on collections

---

src/main/asciidoc/changelog.adoc
src/main/asciidoc/methods.adoc
src/main/asciidoc/resources-collection.adoc
src/main/asciidoc/statuscodes.adoc

Allow response body for resource creation

---

src/main/asciidoc/api_specifications.adoc

Access to documentation resources should be permissive

---

guide/src/main/asciidoc/api_specifications.adoc
guide/src/main/asciidoc/changelog.adoc
guide/src/main/asciidoc/json.adoc
guide/src/main/asciidoc/problems/badRequest.adoc
guide/src/main/asciidoc/versioning.adoc

New rule: unknown request parameters

---

guide/src/main/asciidoc/changelog.adoc
guide/src/main/asciidoc/resources-document.adoc

Naming convention for identifier types

---

guide/src/main/asciidoc/api.adoc

Closes https://github.com/belgif/rest-guide/issues/136

Modify link to SOA article

---

guide/src/main/asciidoc/errorhandling.adoc
guide/src/main/asciidoc/mediatypes.adoc

Changes in RFC: https://www.rfc-editor.org/rfc/rfc9457#name-changes-from-rfc-7807
If OK, I'll update description in belgif openapi-problem as well

Update Problem Details to RFC 9457 which obsoletes RFC7807

---

guide/src/main/asciidoc/resources-collection.adoc

See https://github.com/belgif/rest-guide/issues/25#issuecomment-1706470309.

Mark resource collection items and total properties as required

---

guide/src/main/asciidoc/api_specifications.adoc
guide/src/main/asciidoc/problems/badRequest.adoc

Rename unknown parameter to unknown issue + clarifications

---

guide/src/main/asciidoc/health.adoc

- Create an explicit rule for the health check guidelines
- Make guideline on access restriction of health resource broader #107 
- Specify how clients should interpret unexpected health response

Rework health check rule

---

guide/src/main/asciidoc/resources-document.adoc

Add singleton document with examples

---

guide/src/main/asciidoc/api_specifications.adoc

Additional guidelines on tags (#102)

---

guide/src/main/asciidoc/api_specifications.adoc

Add new rule: required properties should be explicitly declared

---

guide/src/main/asciidoc/api_specifications.adoc

Add that enum values should be valid to their schema

---

guide/src/main/asciidoc/api_specifications.adoc

Add rule: use of operationIds

---

guide/src/main/asciidoc/resources-collection.adoc

Replace 'people' which isn't recommended term

Update collection name example

---

README.md
guide/src/main/asciidoc/api_specifications.adoc
guide/src/main/asciidoc/errorhandling.adoc
guide/src/main/asciidoc/introduction.adoc

Also adds some paragraph titles to intro section

Promote belgif validator and rest-problem-java

---

guide/src/main/asciidoc/internationalization.adoc

Recommend default fallback language when Accept-Language header couldn't be respected (see #205)

Recommend fallback for language negotiation

---

guide/src/main/asciidoc/problems/expiredAccessToken.adoc
guide/src/main/asciidoc/problems/invalidAccessToken.adoc
guide/src/main/asciidoc/problems/missingScope.adoc
guide/src/main/asciidoc/problems/noAccessToken.adoc

Add WWW-Authenticate header for access token or scope problems

---

guide/src/main/asciidoc/api_specifications.adoc
guide/src/main/asciidoc/changelog.adoc
guide/src/main/asciidoc/health.adoc
guide/src/main/asciidoc/mediatypes.adoc
guide/src/main/asciidoc/reserved.adoc
guide/src/main/asciidoc/resources-document.adoc
guide/src/main/asciidoc/resources.adoc
guide/src/main/asciidoc/versioning.adoc

Remove support for OpenAPI 2.0

---

guide/src/main/asciidoc/problems/badRequest.adoc

Add invalidInput issue type

---

guide/src/main/asciidoc/resources-collection.adoc
guide/src/main/asciidoc/resources-document.adoc
guide/src/main/asciidoc/statuscodes.adoc

- describe as conflict with state 'of data on the server' instead of 'of the resource'
- remove optimistic locking from description
related to #217

Update 409 Conflict description

---

guide/pom.xml
guide/src/main/asciidoc/issues/ext/anyOfExpected.adoc
guide/src/main/asciidoc/issues/ext/equalExpected.adoc
guide/src/main/asciidoc/issues/ext/exactlyOneOfExpected.adoc
guide/src/main/asciidoc/issues/ext/invalidPeriod.adoc
guide/src/main/asciidoc/issues/ext/invalidStructure.adoc
guide/src/main/asciidoc/issues/ext/outOfRange.adoc
guide/src/main/asciidoc/issues/ext/rejectedInput.adoc
guide/src/main/asciidoc/issues/ext/requiredInput.adoc
guide/src/main/asciidoc/issues/ext/zeroOrAllOfExpected.adoc
guide/src/main/asciidoc/issues/ext/zeroOrExactlyOneOfExpected.adoc
guide/src/main/asciidoc/issues/invalidInput.adoc
guide/src/main/asciidoc/issues/referencedResourceNotFound.adoc
guide/src/main/asciidoc/issues/schemaViolation.adoc
guide/src/main/asciidoc/issues/unknownInput.adoc
guide/src/main/asciidoc/problems/badRequest.adoc
guide/src/main/asciidoc/resources-document.adoc

URLs providing documentation of input validation issue types
